export const ADD_LIST = "ADD_LIST";
export const ADD_CARD = "ADD_CARD";
export const DRAG_HAPPENED="DRAG_HAPPENED";

export const ADD_LIST_SUCCESS="ADD_LIST_SUCCESS";
export const ADD_LIST_FAILED="ADD_LIST_FAILED";

export const ADD_CARD_SUCCESS="ADD_CARD_SUCCESS";
export const ADD_CARD_FAILED="ADD_CARD_FAILED";

export const LIST_LOADING="LIST_LOADING";
export const LIST_LOADED="LIST_LOADED";
export const LIST_LOADED_FAILED="LIST_LOADED_FAILED"; 

export const USER_LOADING="USER_LOADING";
export const USER_LOADED="USER_LOADED";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const REGISTER_FAIL="REGISTER_FAIL";
export const AUTH_ERROR="AUTH_ERROR";

export const GET_ERRORS="GET_ERRORS";
export const CLEAR_ERRORS="CLEAR_ERRORS";